### ISSUE TITLE
"This regexp should always match" exception

### ISSUE THREAD

**Issue by yarikoptic** [pyout/pyout#104]
Not yet sure if that is my fault, or dependencies, or pyout -- exception message gives me no clues on what went wrong:
```shell
(git-annex)lena:~/proj/dandi/nwb-datasets/nwb_test_data[master]
$> dandi --pdb upload -i local -c nwb_test_data -t . v2.0.0/test_Clustering.nwb
--------------------------------------------------------------------------
[[29421,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: lena

Another transport will be used instead, although this may result in
lower performance.

NOTE: You can disable this warning by setting the MCA parameter
btl_base_warn_component_unused to 0.
--------------------------------------------------------------------------
PATH                       SIZE    ERRORS UPLOAD STATUS                MESSAGE
v2.0.0/test_Clustering.nwb 17.8 kB   0           uploading                    


ERROR: 1 asynchronous worker failed

Producing value for row ('v2.0.0/test_Clustering.nwb',) failed:
Traceback (most recent call last):
  File "/home/yoh/proj/dandi/dandi-cli/venv/dev3/lib/python3.7/site-packages/pyout/interface.py", line 270, in _print_async_exceptions
    future.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/yoh/proj/dandi/dandi-cli/venv/dev3/lib/python3.7/site-packages/pyout/interface.py", line 462, in async_fn
    self._write_async_result(id_vals, cols, i)
  File "/home/yoh/proj/dandi/dandi-cli/venv/dev3/lib/python3.7/site-packages/pyout/interface.py", line 94, in wrapped
    return method(self, *args, **kwds)
  File "/home/yoh/proj/dandi/dandi-cli/venv/dev3/lib/python3.7/site-packages/pyout/interface.py", line 421, in _write_async_result
    self._write(result)
  File "/home/yoh/proj/dandi/dandi-cli/venv/dev3/lib/python3.7/site-packages/pyout/interface.py", line 339, in _write
    self._write_fn(row, style)
  File "/home/yoh/proj/dandi/dandi-cli/venv/dev3/lib/python3.7/site-packages/pyout/interface.py", line 354, in _write_update
    content, status, summary = self._content.update(row, style)
  File "/home/yoh/proj/dandi/dandi-cli/venv/dev3/lib/python3.7/site-packages/pyout/common.py", line 858, in update
    content, status = super(ContentWithSummary, self).update(row, style)
  File "/home/yoh/proj/dandi/dandi-cli/venv/dev3/lib/python3.7/site-packages/pyout/common.py", line 825, in update
    line, adjusted = self.fields.render(row, style)
  File "/home/yoh/proj/dandi/dandi-cli/venv/dev3/lib/python3.7/site-packages/pyout/common.py", line 648, in render
    return self.style["separator_"].join(proc_fields) + "\n", adjusted
  File "/home/yoh/proj/dandi/dandi-cli/venv/dev3/lib/python3.7/site-packages/pyout/common.py", line 647, in <genexpr>
    proc_fields = (fld(val, keys=proc_keys) for fld, val in proc_fields)
  File "/home/yoh/proj/dandi/dandi-cli/venv/dev3/lib/python3.7/site-packages/pyout/field.py", line 155, in __call__
    result = fn(value, result)
  File "/home/yoh/proj/dandi/dandi-cli/venv/dev3/lib/python3.7/site-packages/pyout/field.py", line 472, in split_flanks
    assert match, "This regexp should always match"
AssertionError: This regexp should always match
```

**Comment by yarikoptic** [comment]
the underlying trigger - callback raised an exception

<details>
<summary>traceback from a serial run (without parallel workers)</summary> 

```shell
> dandi --pdb upload -i local -c nwb_test_data -t . v2.0.0/test_Clustering.nwb --develop-debug
--------------------------------------------------------------------------
[[30445,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: lena

Another transport will be used instead, although this may result in
lower performance.

NOTE: You can disable this warning by setting the MCA parameter
btl_base_warn_component_unused to 0.
--------------------------------------------------------------------------
{'size': 17752}
{'status': 'checking girder'}
{'status': 'validating'}
{'errors': 0}
{'status': 'extracting metadata'}
{'status': 'uploading'}
Traceback (most recent call last):
  File "/home/yoh/proj/dandi/dandi-cli/venv/dev3/bin/dandi", line 11, in <module>
    load_entry_point('dandi', 'console_scripts', 'dandi')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/cli/command.py", line 572, in upload
    for v in process_path(path, relpath):
  File "/home/yoh/proj/dandi/dandi-cli/dandi/cli/command.py", line 495, in process_path
    lambda c: client.uploadFileToItem(
  File "/home/yoh/proj/dandi/dandi-cli/dandi/support/generatorify.py", line 83, in __next__
    return self.send(None)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/support/generatorify.py", line 77, in send
    return self._put("send", value)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/support/generatorify.py", line 69, in _put
    raise val
  File "/home/yoh/proj/dandi/dandi-cli/dandi/support/generatorify.py", line 53, in thread_func
    ret = func(callback)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/cli/command.py", line 496, in <lambda>
    item_rec["_id"], path, progressCallback=c
  File "/home/yoh/proj/dandi/dandi-cli/venv/dev3/lib/python3.7/site-packages/girder_client/__init__.py", line 887, in uploadFileToItem
    obj = self.post('file', params)
  File "/home/yoh/proj/dandi/dandi-cli/venv/dev3/lib/python3.7/site-packages/girder_client/__init__.py", line 495, in post
    data=data, json=json, headers=headers, jsonResp=jsonResp)
  File "/home/yoh/proj/dandi/dandi-cli/venv/dev3/lib/python3.7/site-packages/girder_client/__init__.py", line 481, in sendRestRequest
    response=result)
girder_client.HttpError: HTTP error 500: POST http://localhost:8080/api/v1/file?parentType=item&parentId=5e3324344470b500f42dd671&name=test_Clustering.nwb&size=17752
Response text: {"identifier": "girder.model.assetstore.no-current-assetstore", "message": "No current assetstore is set.", "type": "girder"}

> /home/yoh/proj/dandi/dandi-cli/venv/dev3/lib/python3.7/site-packages/girder_client/__init__.py(481)sendRestRequest()
-> response=result)
```
</details>

**Comment by kyleam** [comment]
> Not yet sure if that is my fault, or dependencies, or pyout -- exception message gives me no clues on what went wrong

I'll try to come up with a minimal example that triggers it (based on your next post, probably needs a callback that raises an exception).

This is pyout's fault.  That `assert` is a proper debugging assert, meaning that regexp that should, er, always match.  There's a bug in the logic somewhere.

**Comment by kyleam** [comment]
I'm still not seeing how to trigger that.  Could you apply this patch and tell me what `result` looks like?

```diff
diff --git a/pyout/field.py b/pyout/field.py
index 96590567..d5f5a6ac 100644
--- a/pyout/field.py
+++ b/pyout/field.py
@@ -469,7 +469,8 @@ def split_flanks(self, _, result):
             return result
 
         match = self.flank_re.match(result)
-        assert match, "This regexp should always match"
+        if not match:
+            import ipdb as pdb; pdb.set_trace()
         self.left, self.right = match.group(1), match.group(3)
         return match.group(2)
 
```

**Comment by yarikoptic** [comment]
crap... cannot reproduce now even after I removed girder's assert store, went back to that state of dandi-cli (but may be it was some dirty git state :-/) and getting the same exception from girder -- but pyout doesn't trigger that assertion. I should have reproman traced it or smth like that to bring things back into exactly the same shape.  But why not to include  `result` into exception message?  I would have then made explicit 
```python
if not match:
     raise RintimeError("Flank regexp should always match, but failed on %s" % repr(result))
```
or smth like that.  Then on the next similar case, we would automagically get desired value of the result

**Comment by kyleam** [comment]
> But why not to include `result` into exception message?

Yeah, I'd lean that way too.  But then I'd have to hear you complain about lower test coverage for something that I do no know how to trigger and cannot test.  Even though that lower coverage is absolutely not an indication of a problem, I'd have to argue that, and it's not worth that headache for a bit of code that, to my knowledge, was unreachable.

**Comment by yarikoptic** [comment]
Let's not jump ahead with assumptions on what I would complain about ;-) Thanks for the commit!

**Comment by kyleam** [comment]
> Let's not jump ahead with assumptions on what I would complain about ;-)

We've already had similar discussions about coverage in pyout and elsewhere in the past.  So what you're saying comes down to "don't use your prior experience of how I've reacted in the past to predict what my opinions/reactions are today".  Sorry, that just isn't tenable for me (or anyone, really).
