### ISSUE TITLE
RedoContent bubbles up into the "user land"

### ISSUE THREAD

**Issue by yarikoptic** [pyout/pyout#114]
I was test driving the #113 (merged, using v0.6.1-7-g04627d1 now) , while messing with a terminal size and making it relatively small, got:
 
```shell
$> DANDI_CACHE=ignore dandi ls ../nwb-datasets/*/*/*nwb     
PATH                     SIZE   GEN... AGE   SES... SUB... SEX INS... #EL... IDE... NWB   SPE... SES... SES... ND_... PRO...
...149/sub-759711149.nwb 2.3 GB                                                                                             
...792602650_ecephys.nwb 1.8 GB wt/wt  P114D 774... 759... M   All... 70     792... 2.2.2 Mus... LFP... 201... Dyn... 792...
...792602652_ecephys.nwb 2.2 GB wt/wt  P114D 774... 759... M   All... 87     792... 2.2.2 Mus... LFP... 201... Dyn... 792...
...792602654_ecephys.nwb 1.7 GB wt/wt  P114D 774... 759... M   All... 65     792... 2.2.2 Mus... LFP... 201... Dyn... 792...
...792602656_ecephys.nwb 1.7 GB wt/wt  P114D 774... 759... M   All... 65     792... 2.2.2 Mus... LFP... 201... Dyn... 792...
...792602658_ecephys.nwb 2.0 GB wt/wt  P114D 774... 759... M   All... 77     792... 2.2.2 Mus... LFP... 201... Dyn... 792...
...00_ses-816200189_.nwb 2.4 GB                                                                                             
...j-160etlc_ecephys.nwb 2.6 GB Vip... P128D 816... 791... F   All... 87     836... 2.2.2 Mus... LFP... 201... Dyn... 836...
...j-1isk427_ecephys.nwb 2.6 GB Vip... P128D 816... 791... F   All... 96     836... 2.2.2 Mus... LFP... 201... Dyn... 836...
...29_ses-819701982_.nwb                                                                                                    
...j-147k4o6_ecephys.nwb                                                                                                    
...j-1ad8p0q_ecephys.nwb                                                                                                    

RedoContent() raised
Canceled pending asynchronous workers. 2 workers already running
Error: 
DANDI_CACHE=ignore dandi ls ../nwb-datasets/*/*/*nwb  11.03s user 0.44s system 102% cpu 11.150 total
```

I do not remember exact sequence of "actions" which triggered it.  In 2nd try I started with a small one, and made it larger (vertically and horizontally) while it was still waiting for callbacks to report back.  This time a bit more information surfaced:
```
...s-20170214T211953.nwb                                                                                                       
2020-08-27 09:11:04,776 [   ERROR] exception calling callback for <Future at 0x7fb2d0c0bf10 state=finished returned dict>
Traceback (most recent call last):
  File "/home/yoh/proj/repronim/pyout/pyout/common.py", line 800, in __str__
    return "".join(self._render(self.rows))
  File "/home/yoh/proj/repronim/pyout/pyout/common.py", line 796, in _render
    raise RedoContent
pyout.common.RedoContent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/home/yoh/proj/repronim/pyout/pyout/interface.py", line 490, in callback
    self._write_async_result(
  File "/home/yoh/proj/repronim/pyout/pyout/interface.py", line 95, in wrapped
    return method(self, *args, **kwds)
  File "/home/yoh/proj/repronim/pyout/pyout/interface.py", line 441, in _write_async_result
    self._write(result)
  File "/home/yoh/proj/repronim/pyout/pyout/interface.py", line 356, in _write
    self._write_fn(row, style)
  File "/home/yoh/proj/repronim/pyout/pyout/interface.py", line 375, in _write_update
    content, status, summary = self._content.update(row, style)
  File "/home/yoh/proj/repronim/pyout/pyout/common.py", line 926, in update
    content, status = super(ContentWithSummary, self).update(row, style)
  File "/home/yoh/proj/repronim/pyout/pyout/common.py", line 895, in update
...60826T221752_icephys.nwb 29.0 MB          2.2.2 Allen...                   c7a14...     541516760                   PLACE... Curre... 2016-...             
...60826T232446_icephys.nwb 37.0 MB          2.2.2 Allen...                   fa66c...     541516760                   PLACE... Curre... 2016-...             
    return "".join(self._render(self.rows))
  File "/home/yoh/proj/repronim/pyout/pyout/common.py", line 796, in _render
..._ses-20170214T213024.nwb                                                                                                                                   
..._ses-20170301T011851.nwb                                                                                                                                   
..._ses-20170301T172948.nwb                                                                                                                                   
Summary:                    19.3 GB                                                                                                      2016-...             
                                                                                                                                         2019-...             
^C
KeyboardInterrupt() raised
Canceled pending asynchronous workers. 0 workers already running
```

I have triggered the same fail then solely by expanding the terminal.

**Comment by kyleam** [comment]
Thanks for giving it a try.  I can trigger it on my end with `dandi ls`, but I haven't yet isolated what the problem is.

**Comment by kyleam** [comment]
At least on my end, this issue is avoided with 420ea6d2 (Content: Try rendering three times to work around unsolved bug, 2020-09-19).  That of course isn't a proper solution.
