### ISSUE TITLE
my neck hurts from "See[ing] above"

### ISSUE THREAD

**Issue by yarikoptic** [pyout/pyout#43]
Thought to give a shot at a script sketch so there is no datalad needed/involved but failed with our favorite exception and this time there were no 'above' exception listing:
```shell
$> echo '{"a":1, "b": true, "c": null}'| PYTHONPATH=$PWD/.. ./color_json.py
Traceback (most recent call last):
  File "./color_json.py", line 26, in <module>
    out(line_json)
  File "/home/yoh/proj/repronim/pyout/pyout/tabular.py", line 549, in __call__
    self._maybe_write_header()
  File "/home/yoh/proj/repronim/pyout/pyout/tabular.py", line 398, in _maybe_write_header
    adopt=False, repaint=False)
  File "/home/yoh/proj/repronim/pyout/pyout/tabular.py", line 367, in _check_and_write
    self._set_widths(row, proc_group)
  File "/home/yoh/proj/repronim/pyout/pyout/tabular.py", line 278, in _set_widths
    exclude_post=True)
  File "/home/yoh/proj/repronim/pyout/pyout/field.py", line 144, in __call__
    result = fn(value, result)
  File "/home/yoh/proj/repronim/pyout/pyout/field.py", line 268, in transform_fn
    raise StyleFunctionError(function)
pyout.field.StyleFunctionError: Style transform <method 'upper' of 'str' objects> raised an exception. See above.
```

**Comment by kyleam** [comment]
Yes, as we already discussed wrt datalad, I'll rework how this is displayed
