### ISSUE TITLE
gets stuck or pukes error if there is "interval" but value is a string

### ISSUE THREAD

**Issue by yarikoptic** [pyout/pyout#91]
torturing pyout via dandi

I have
```
        "errors": dict(
            color=dict(
                interval=[
                    [0, 1, "green"],
                    [1, None, "red"],
                ]
            ),
            aggregate=lambda x: "{} with errors".format(sum(map(bool, x))),
        ),
```
and if I yield an empty string as a value - usually stalls, but once actually crashed and gave me error

```
$> dandi upload -i local -c upload2 -t /tmp --validation skip /tmp/nwb_test_data/v2.0.0/test_*nwb
PATH                                 SIZE    ERRORS        UPLOAD STATUS MESSAGE
Traceback (most recent call last):
  File "/home/yoh/proj/dandi/dandi-cli/venvs/dev3/bin/dandi", line 11, in <module>
    load_entry_point('dandi', 'console_scripts', 'dandi')()
  File "/home/yoh/proj/misc/click/click/core.py", line 828, in __call__
    return self.main(*args, **kwargs)
  File "/home/yoh/proj/misc/click/click/core.py", line 781, in main
    rv = self.invoke(ctx)
  File "/home/yoh/proj/misc/click/click/core.py", line 1227, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yoh/proj/misc/click/click/core.py", line 1046, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yoh/proj/misc/click/click/core.py", line 590, in invoke
    return callback(*args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/cli/command.py", line 462, in upload
    out(rec)
  File "/home/yoh/proj/repronim/pyout/pyout/interface.py", line 384, in __call__
    self._write(row, style)
  File "/home/yoh/proj/repronim/pyout/pyout/interface.py", line 236, in _write
    self._write_fn(row, style)
  File "/home/yoh/proj/repronim/pyout/pyout/interface.py", line 249, in _write_update
    content, status, summary = self._content.update(row, style)
  File "/home/yoh/proj/repronim/pyout/pyout/common.py", line 701, in update
    content, status = super(ContentWithSummary, self).update(row, style)
  File "/home/yoh/proj/repronim/pyout/pyout/common.py", line 672, in update
    return six.text_type(self), "repaint"
  File "/home/yoh/proj/repronim/pyout/pyout/common.py", line 611, in __str__
    return "".join(self._render(self.rows))
  File "/home/yoh/proj/repronim/pyout/pyout/common.py", line 601, in _render
    line, adj = self.fields.render(row, **kwds)
  File "/home/yoh/proj/repronim/pyout/pyout/common.py", line 523, in render
    for c in self.columns if not hidden[c]]
  File "/home/yoh/proj/repronim/pyout/pyout/common.py", line 523, in <listcomp>
    for c in self.columns if not hidden[c]]
  File "/home/yoh/proj/repronim/pyout/pyout/field.py", line 158, in __call__
    result = fn(value, result)
  File "/home/yoh/proj/repronim/pyout/pyout/field.py", line 381, in proc
    value = float(value)
ValueError: could not convert string to float: 
(dev3) 1 37143 ->1 [2].....................................:Fri 18 Oct 2019 12:31:28 PM EDT:.
(git)hopa:~/proj/dandi/dandi-cli[nf-upload]git
$> dandi upload -i local -c upload2 -t /tmp --validation skip /tmp/nwb_test_data/v2.0.0/test_*nwb
PATH                                     SIZE    ERRORS        UPLOAD STATUS MESSAGE
nwb_test_data/v2.0.0/test_append.nwb     43.1 kB                                    
^[[a^C
Aborted!
```

from traceback above seems like might relate to use of `interval` since otherwise there should be no reason for float conversion

**Comment by kyleam** [comment]
That fact that it's stalling is unfortunate.  Trying with various examples, I can't trigger that.  All of this happens outside of the callbacks, so I'd hope it wouldn't be plagued by the same hanging with silent failures.

The intended behavior here is to error if given a value that can't be converted to a float (with the exception of missing values, represented by the `Nothing` class).  We could change this to catch the ValueError and swallow it as a logged warning, but no regular user will see that.  Another option would be to collect the failures and then display (or return them to the caller to deal with) after Tabular has exited.  But given that something like that isn't wired up, the intention was to alert the caller to the invalid value.

That being said, some specific pyout exception should be raised rather than a plain ValueError.  That would allow the caller to catch that and do whatever they think is most appropriate.

---


IIRC your style definition won't do what you want even if all the above worked they way you wanted.  The style for the "errors" column isn't propagated to the corresponding summary field.  You can style summary columns via `aggregate_`, but that will apply to all summary fields.

**Comment by kyleam** [comment]
I said:
> The intended behavior here is to error if given a value that can't be converted to a float (with the exception of missing values, represented by the `Nothing` class).

Thinking more about this, I don't think the original strictness is needed.  It is purely a matter of styling, so leaving things that can't be cast as floats as is should be fine.
